services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik" 
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/letsencrypt:/letsencrypt"
      - ./traefik.yml:/etc/traefik/traefik.yml:ro

  apache:
    image: "httpd:latest"
    container_name: "apache"
    labels:
      - traefik.enable=true
      - traefik.http.routers.apache.rule=Host(`<your.domain.com>`)
      - traefik.http.routers.apache.entrypoints=websecure
      - traefik.http.routers.apache.tls=true
      - traefik.http.routers.apache.tls.certresolver=letsencrypt

networks:
  default:
    external: true
    name: traefik-net