services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  apache:
    image: "httpd:latest"
    container_name: "apache"
    labels:
     - traefik.enable=true
     - traefik.http.routers.apache.rule=Host(`<your.domain.com>`)
     - traefik.http.routers.apache.entrypoints=web

